### ISSUE TITLE
~/.local/bin/ directory didn't exist, binaries didn't install properly.

### ISSUE THREAD

**Issue by imNel** [mrniceguy127/osu-wine-install-script#3]
Making the directory and relaunching the script worked though. Potentially add the mkdir to the script?

**Comment by mrniceguy127** [comment]
Yeah, good catch I'll add that. Thanks

**Comment by mrniceguy127** [comment]
Just pushed a fix in 5a9b239dd904083e827b0f99edbe89eea64bacb6 !
